pipeline {
    agent any

    tools {
        jdk 'jdk17'
        maven 'maven-3.9'
    }

    environment {
        PROJECT_KEY = "my-java-app"

        AWS_REGION = "ap-south-2"
        ECR_REPO   = "692614315837.dkr.ecr.ap-south-2.amazonaws.com/myrepo"

        NEXUS_URL  = "http://172.31.4.228:32081"
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Sonar Analysis') {
            steps {
                dir('my-java-app') {
                    withSonarQubeEnv('SonarQube-Server') {
                        withCredentials([
                            string(credentialsId: 'jenkins-token', variable: 'SONAR_TOKEN')
                        ]) {
                            sh '''
                            mvn clean verify sonar:sonar \
                              -Dsonar.projectKey=${PROJECT_KEY} \
                              -Dsonar.projectName=${PROJECT_KEY} \
                              -Dsonar.token=$SONAR_TOKEN
                            '''
                        }
                    }
                }
            }
        }

       stage('Build & Deploy to Nexus') {
          steps {
             dir('my-java-app') {
                 withMaven(
                    maven: 'maven-3.9',
                    mavenSettingsConfig: '44078b5b-9b6a-4b82-bc08-f9b17fc41e1f'
                    ) {
                         sh 'mvn clean deploy -DskipTests'
            }
        }
    }
}


        stage('Build Docker Image') {
            steps {
                dir('my-java-app') {
                    sh '''
                    cp target/*.jar app.jar
                    docker build -t myapp:${IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('Login to AWS ECR') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: 'aws-creds']
                ]) {
                    sh '''
                    aws ecr get-login-password --region $AWS_REGION \
                    | docker login --username AWS --password-stdin $ECR_REPO
                    '''
                }
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh '''
                docker tag myapp:${IMAGE_TAG} $ECR_REPO:${IMAGE_TAG}
                docker push $ECR_REPO:${IMAGE_TAG}
                '''
            }
        }
    }

    post {
        success {
            echo "✅ CI + CD PIPELINE SUCCESSFUL"
        }
        failure {
            echo "❌ PIPELINE FAILED"
        }
    }
}
