pipeline {
    agent any

    tools {
        jdk 'jdk17'
        maven 'maven-3.9'
    }

    environment {
        PROJECT_KEY = "my-java-app"

        AWS_REGION = "ap-south-2"
        ECR_REPO = "692614315837.dkr.ecr.ap-south-2.amazonaws.com/myrepo"

        NEXUS_URL  = "http://18.61.211.143:32081"
        NEXUS_REPO = "http://18.61.211.143:32081/repository/maven-releases/"

        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Sonar Analysis') {
            steps {
                dir('my-java-app') {
                    withSonarQubeEnv('SonarQube-Server') {
                        withCredentials([
                            string(credentialsId: 'jenkins-token', variable: 'SONAR_TOKEN')
                        ]) {
                            sh '''
                              mvn clean verify sonar:sonar \
                                -Dsonar.projectKey=${PROJECT_KEY} \
                                -Dsonar.projectName=${PROJECT_KEY} \
                                -Dsonar.token=$SONAR_TOKEN
                            '''
                        }
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build & Package') {
            steps {
                dir('my-java-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Upload Artifact to Nexus') {
            steps {
                dir('my-java-app') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'nexus-creds',
                            usernameVariable: 'NEXUS_USER',
                            passwordVariable: 'NEXUS_PASS'
                        )
                    ]) {
                        sh """
                        curl -u $NEXUS_USER:$NEXUS_PASS \
                        --upload-file target/*.jar \
                        $NEXUS_URL/repository/$NEXUS_REPO/my-java-app-${BUILD_NUMBER}.jar
                        """
                    }
                }
            }
        }

        stage('Build Docker Image (Pull from Nexus)') {
            steps {
                sh """
                curl -o app.jar \
                $NEXUS_URL/repository/$NEXUS_REPO/my-java-app-${BUILD_NUMBER}.jar

                docker build -t myapp:${IMAGE_TAG} .
                """
            }
        }

        stage('Login to AWS ECR') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: 'aws-creds']
                ]) {
                    sh """
                    aws ecr get-login-password --region $AWS_REGION \
                    | docker login --username AWS --password-stdin $ECR_REPO
                    """
                }
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh """
                docker tag myapp:${IMAGE_TAG} $ECR_REPO:${IMAGE_TAG}
                docker push $ECR_REPO:${IMAGE_TAG}
                """
            }
        }
    }

    post {
        success {
            echo "✅ CI + CD PIPELINE SUCCESSFUL"
        }
        failure {
            echo "❌ PIPELINE FAILED"
        }
    }
}
